- configure script to automtically generate Makefile.config - GNU sed macros replaced with perl
git-svn-id: svn+ssh://scm.gforge.inria.fr/svnroot/mlxxxidl/mlgmpidl/trunk@328 c27d38ec-fa33-0410-b621-fb01b97e5d69

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,54 +1,443 @@
-#!/bin/sh
+#! /bin/sh
 
-# ------------------------------------------------------------------------------
+# configuration script for mlgmpidl
+# based on the configure script from apron
+#
+# generates automatically a suitable Makefile.config
 
-# utils
 
-warn () { echo "$1" >/dev/stderr; }
-info () { echo "$1" >/dev/stderr; }
-err () { echo "$1" >/dev/stderr; exit 1; }
-arg () { test "x$2" != "x" && echo "$2" || err "Missing argument for \`$1'!"; }
+##############################################
+# help
+#######
 
-# arg. parsing
+help()
+{
+    cat <<EOF
+usage: configure [options]
 
-while test $# '>' 0; do
-    case "$1" in
-	*) warn "Ignoring argument \`$1'!"; shift;;
-    esac;
-done;
+where options include:
+  -prefix dir          installation directory
+  -gmp-prefix dir      where to find the GMP library
+  -mpfr-prefix dir     where to find the MPFR library
+  -no-ocamlfind        disable OCamlfind support
+  -absolute-dylibs     force absolute library names (OSX only)
 
-# ---
+Environment variables that affect configuration:
+  CC                   C compiler to use (default: gcc)
+  CFLAGS               extra flags to pass to the C compiler
+  LDFLAGS              extra link flags
+  GMP_PREFIX           where to find the GMP library
+  MPFR_PREFIX          where to find the MPFR library
 
-# output config file
-exec 1>"Makefile.config";
-cat Makefile.config.in;
-
-maybe_cmd () {
-    command -v $2 >/dev/null && echo "$1 = $2" || warn "$3 seems unavailable";
+EOF
+    exit
 }
 
-system=$(uname -s);
-info "Detected System: ${system}"; 
-case "${system}" in
-    Linux)  
-	:;;			# <- defaults are ok.
-    Darwin|FreeBSD) 
-	echo 'GMP_PREFIX = /usr/local';
-	echo 'MPFR_PREFIX = /usr/local';
-	maybe_cmd "SED" "gsed" "GNU sed";;
-    *)
-	err "Unknown System!";;
-esac;
 
-overs=$(ocamlc -version);
-case "${overs}" in
-    [1-3].* | 4.01.*)
-	err "OCaml version found is ${overs}: OCaml >= 4.02 is required.";;
-    *)
-	:;;
- esac
+##############################################
+# parse arguments
+#################
 
-info "Plugins will be built.";
-echo 'HAS_NATIVE_PLUGINS = 1';
+mlgmpidl_prefix=/usr/local
+has_cxx=1
+has_ppl=1
+has_ocamlfind=1
+force_absolute_dylib_install_names=0;
+while : ; do
+    case "$1" in
+        "") 
+            break;;
+        -prefix|--prefix)
+            mlgmpidl_prefix="$2"
+            shift;;
+        -gmp-prefix|--gmp-prefix)
+            gmp_prefix="$2"
+            shift;;
+        -mpfr-prefix|--mpfr-prefix)
+            mpfr_prefix="$2"
+            shift;;
+        -no-ocamlfind|--no-ocamlfind)
+            has_ocamlfind=0;;
+	-absolute-dylibs|--absolute-dylibs)
+	    force_absolute_dylib_install_names=1;;
+        -help|--help)
+            help;;
+        *)
+            echo "unknown option $1, try -help"
+            exit 2;;
+    esac
+    shift
+done
 
-# ------------------------------------------------------------------------------
+
+##############################################
+# utilities
+###########
+
+# print utility
+echo_n()
+{
+    echo "$1" | tr -d '\012'
+}
+
+
+# checkcc cc opt
+# checks that compiler cc can compile a simple program with option opt
+# if so, add it to acc
+checkcomp()
+{
+    testcc="$1"
+    testopt="$2";
+    echo_n "checking compilation with $testcc $testopt: "
+    rm -f tmp.c tmp.out
+    echo "int main() { return 1; }" >> tmp.c
+    r=1
+    $testcc $testopt tmp.c -o tmp.out >/dev/null 2>/dev/null || r=0
+    if test ! -x tmp.out; then r=0; fi
+    rm -f tmp.c tmp.o tmp.out
+    if test $r -eq 0; then
+        echo "not working"
+    else
+        acc="$acc $testopt"
+        echo "working"
+    fi
+    return $r
+}
+
+
+# checking include file
+checkinc()
+{
+    testcc="$1"
+    testinc="$2"
+    echo_n "include $testinc: "
+    rm -f tmp.c tmp.o
+    echo "#include <$testinc>" > tmp.c
+    echo "int main() { return 1; }" >> tmp.c
+    r=1
+    $testcc -c tmp.c -o tmp.o >/dev/null 2>/dev/null || r=0
+    if test ! -f tmp.o; then r=0; fi
+    rm -f tmp.c tmp.o
+    if test $r -eq 0; then echo "not found"; else echo "found"; fi
+    return $r
+}
+
+
+# checking library
+checklib()
+{
+    testcc="$1"
+    testlib="$2"
+    echo_n "library $testlib: "
+    rm -f tmp.c tmp.out
+    echo "int main() { return 1; }" >> tmp.c
+    r=1
+    $testcc tmp.c -l$testlib -o tmp.out >/dev/null 2>/dev/null || r=0
+    if test ! -x tmp.out; then r=0; fi
+    rm -f tmp.c tmp.o tmp.out
+    if test $r -eq 0; then echo "not found"; else echo "found"; fi
+    return $r
+}
+
+
+# checkprefix include lib
+#
+# tries to find a prefix needed to get the library
+checkprefix()
+{
+    testcc="$1"
+    testinc="$2"
+    testlib="$3"
+    testprefix="$4"
+    # try without any prefix (unless the user forced a prefix)
+    if test "x$testprefix" = "x"
+    then
+        echo "looking for $testlib without prefix"
+        prefix=""
+        checkinc "$testcc" "$testinc"
+        if test $r -eq 1
+        then
+            checklib "$testcc" "$testlib"
+            if test $r -eq 1
+            then
+                echo "library $testlib found without prefix"
+                return 1
+            fi
+        fi
+    fi
+    # check with a prefix
+    for prefix in $testprefix /usr/local /usr "$HOME"
+    do
+        echo "looking for $testlib in prefix $prefix"
+        checkinc "$testcc -I$prefix/include" "$testinc"
+        if test $r -eq 1
+        then
+            checklib "$testcc -L$prefix/lib" "$testlib"
+            if test $r -eq 1
+            then
+                echo "library $testlib found with prefix $prefix"
+                return 1
+            fi
+        fi
+    done
+    echo "library $testlib not found"
+    return 0
+}
+
+
+
+# checking binaries in $PATH
+
+searchbin()
+{
+    if test "x$1" = "x"; then return 0; fi
+    echo_n "binary $1: "
+    IFS=':'
+    path=""
+    for i in $PATH
+    do
+        if test -z "$i"; then i='.'; fi
+        if test -x "$i/$1"
+        then
+            echo "found in $i"
+            path="$i/$1"
+            unset IFS
+            return 1
+        fi
+    done
+    echo "not found"
+    unset IFS
+    return 0
+}
+
+searchbinreq()
+{
+    searchbin $1
+    if test $? -eq 0; then echo "required program $1 not found"; exit 1; fi
+}
+
+checkdirinpath()
+{
+    dir="$1"
+    path="$2"
+    echo_n "checking whether $1 belongs to $3: "
+    # env bash -c '[[ ":'${path}':" == *":'${dir}':"* ]]';
+    # if test $? -eq 1; then echo "no"; return 1; fi
+    IFS=':'
+    found=0
+    for d in $path
+    do
+	if test "$d" -ef "$dir"; then found=1; fi
+    done
+    unset IFS;
+    if test $found -eq 0; then echo "no"; return 1; fi
+    echo "yes"
+}
+
+#####################################
+# tests
+#######
+
+c_flags="-Wcast-qual -Wswitch -Wall -Wextra -Wundef -Wcast-align -Wno-unused -Wno-unused-parameter -Wno-unused-function -fPIC"
+
+
+# C compiler
+
+cc="none"
+for i in $CC cc gcc
+do
+    checkcomp "$i" ""
+    if test $? -eq 1; then cc="$i"; break; fi
+done
+if test "$cc" = "none"; then echo "no C compiler found"; exit 1; fi
+
+acc=""
+for i in $c_flags -Werror-implicit-function-declaration -Wbad-function-cast -Wstrict-prototypes -std=c99 $CFLAGS $LDFLAGS
+do
+    checkcomp "$cc" "$i"
+done
+cflags=$acc
+
+
+# tools
+
+searchbinreq "ar"; ar="$path"
+searchbinreq "ranlib"; ranlib="$path"
+searchbinreq "sed"; sed="$path"
+searchbinreq "perl"; perl="$path"
+searchbinreq "install"; install="$path"
+
+
+# C libraries
+
+if test "x$gmp_prefix" != "x"; then GMP_PREFIX="$gmp_prefix"; fi
+checkprefix "$cc $cflags" gmp.h gmp "$GMP_PREFIX"
+if test $? -eq 0; then echo "GMP not found, set GMP_PREFIX"; exit 1; fi
+gmp_prefix="$prefix"
+
+if test "x$mpfr_prefix" != "x"; then MPFR_PREFIX="$mpfr_prefix"; fi
+checkprefix "$cc $cflags" mpfr.h mpfr "$MPFR_PREFIX"
+if test $? -eq 0; then echo "MPFR not found, set MPFR_PREFIX"; exit 1; fi
+mpfr_prefix="$prefix"
+
+# OCaml environment
+
+# check OCaml binaries
+has_ocaml=1
+if test $has_ocaml -eq 1; then searchbin "ocamlc.opt"; has_ocaml=$?; ocamlc="$path"; fi
+if test $has_ocaml -eq 1; then searchbin "ocamlopt.opt"; has_ocaml=$?; ocamlopt="$path"; fi
+if test $has_ocaml -eq 1; then searchbin "ocamldep"; has_ocaml=$?; ocamldep="$path"; fi
+if test $has_ocaml -eq 1; then searchbin "ocamldoc"; has_ocaml=$?; ocamldoc="$path"; fi
+if test $has_ocaml -eq 1; then searchbin "ocamlmktop"; has_ocaml=$?; ocamlmktop="$path"; fi
+if test $has_ocaml -eq 1; then searchbin "ocamlmklib"; has_ocaml=$?; ocamlmklib="$path"; fi
+if test $has_ocaml -ne 1; then "OCaml not found"; exit 1; fi
+
+if test $has_ocaml -eq 1; then searchbin "camlidl"; has_ocaml=$?; camlidl="$path"; fi
+if test $has_ocaml -ne 1; then "OCamlIDL not found"; exit 1; fi
+
+# optional ocamlfind
+if test $has_ocamlfind -eq 1
+then
+    has_ocamlfind=0
+    if test $has_ocaml -eq 1; then searchbin "ocamlfind"; has_ocamlfind=1; ocamlfind="$path"; fi
+fi
+
+# guess prefix
+if test $has_ocamlfind -eq 1
+then
+    caml_prefix=`$ocamlfind printconf stdlib`
+    camlidl_prefix=`$ocamlfind query camlidl`
+    if test "x$camlidl_prefix" = "x"; then camlidl_prefix=`$ocamlc -where`; fi
+    mlgmpidl_prefix=`$ocamlfind query gmp`
+    if test "x$mlgmpidl_prefix" = "x"; then mlgmpidl_prefix=`$ocamlc -where`; fi
+else
+    # sane default (but does not work with OPAM)
+    caml_prefix=`$ocamlc -where`
+    camlidl_prefix=`$ocamlc -where`
+    mlgmpidl_prefix=`$ocamlc -where`
+fi
+
+# check that the prefix is correct
+if test $has_ocaml -eq 1
+then
+    checkinc "$cc $cflags -I$caml_prefix" caml/mlvalues.h
+    has_ocaml=$?
+fi
+if test $has_ocaml -eq 1
+then
+    checkinc "$cc $cflags -I$caml_prefix -I$camlidl_prefix" caml/camlidlruntime.h
+    has_ocaml=$?
+fi
+if test $has_ocaml -eq 1
+then
+    cc_cmd="$cc $cflags -I$caml_prefix -I$mlgmpidl_prefix";
+    if test "x$gmp_prefix" != "x"; then cc_cmd="$cc_cmd  -I$gmp_prefix/include"; fi
+fi
+if test $has_ocaml -ne 1; then "OCaml not found"; exit 1; fi
+
+##############################################
+# Custom tests
+##############
+
+# Use abolute dynamic library names under OSX when explicitly asked,
+# or when the installation prefix does not belong to DYLD_LIBRARY_PATH
+# nor DYLD_FALLBACK_LIBRARY_PATH or
+# '$(HOME)/lib:/usr/local/lib:/lib:/usr/lib' (the default fallback).
+absolute_dylib_install_names=;
+if test "x$(uname -s)" = "xDarwin"
+then
+    if test $force_absolute_dylib_install_names -eq 1
+    then
+	echo "using absolute dynamic library install names as requested"
+	absolute_dylib_install_names=1
+    else
+	libdir="${mlgmpidl_prefix}/lib"
+	if test "x$DYLD_FALLBACK_LIBRARY_PATH" != "x"
+	then
+	    fldpath="$DYLD_FALLBACK_LIBRARY_PATH"
+	else
+	    fldpath="$HOME/lib:/usr/local/lib:/lib:/usr/lib"
+	fi
+	checkdirinpath "${libdir}" "$DYLD_LIBRARY_PATH" "DYLD_LIBRARY_PATH" || \
+	    checkdirinpath "${libdir}" "${fldpath}" "DYLD_FALLBACK_LIBRARY_PATH"
+	if test $? -eq 1
+	then
+	    echo "forcing absolute dynamic library install names"
+	    absolute_dylib_install_names=1
+	fi
+    fi
+else
+    if test $force_absolute_dylib_install_names -eq 1
+    then
+	echo "ignoring option \`-absolute-dylibs', only meaningful under OSX";
+    fi
+fi
+
+
+##############################################
+# log
+#####
+
+cat <<EOF
+
+detected configuration:
+
+   optional OCamlFind support   $has_ocamlfind
+
+   installation path            $mlgmpidl_prefix
+
+EOF
+
+test "x$absolute_dylib_install_names" = "x1" && cat <<EOF
+   dynamic libraries shall use absolute install names
+
+EOF
+
+##############################################
+# generation
+############
+
+cat > Makefile.config <<EOF
+# generated by ./configure
+
+HAS_SHARED = 1
+HAS_OCAMLOPT = 1
+
+MLGMPIDL_PREFIX = $mlgmpidl_prefix
+
+GMP_PREFIX = $gmp_prefix
+MPFR_PREFIX = $mpfr_prefix
+
+CC = $cc
+CFLAGS = -U__STRICT_ANSI__ -DNDEBUG -O3 $cflags
+CFLAGS_DEBUG = -U__STRICT_ANSI__ -UNDEBUG -O0 -g $cflags
+
+AR = $ar
+RANLIB = $ranlib
+SED = $sed
+PERL = $perl
+INSTALL = $install
+INSTALLd = $install -d
+
+CAML_PREFIX = $caml_prefix
+CAMLIDL_PREFIX = $camlidl_prefix
+OCAMLC = $ocamlc
+OCAMLOPT = $ocamlopt
+OCAMLFLAGS = -annot -g
+OCAMLOPTFLAGS = -annot -inline 20
+OCAMLDEP = $ocamldep
+OCAMLDOC = $ocamldoc
+OCAMLMKTOP = $ocamlmktop
+OCAMLMKLIB = $ocamlmklib
+CAMLIDL = $camlidl
+OCAMLFIND = $ocamlfind
+
+# TODO: to be configured
+LATEX = latex
+DVIPDF = dvipdf
+MAKEINDEX = makeindex
+
+# OSX only:
+ABSOLUTE_DYLIB_INSTALL_NAMES = $absolute_dylib_install_names
+
+EOF
